const logs = [
  {
    key: "1",
    dateAccomplished: "2024-09-16",
    workDone: "Created Website",
    membersParticipated: "Russell",
  },
  {
    key: "2",
    dateAccomplished: "2024-09-17",
    workDone:
      "Researched avalible professors from MME, ECE, BME, SYDE, and Optomitry to see who could possibly help us and provide more information.",
    membersParticipated: "All Team members",
  },
  {
    key: "3",
    dateAccomplished: "2024-09-20",
    workDone: "Updated website to use react and implemnted a log book",
    membersParticipated: "Harsimrat",
  },
  {
    key: "4",
    dateAccomplished: "2024-09-27",
    workDone:
      "Researched and came up with 4 possible solutions as well as 3 Patents",
    membersParticipated: "All Team members",
  },
  {
    key: "5",
    dateAccomplished: "2024-10-4",
    workDone: "Started research into AI models and tech required for project",
    membersParticipated: "Russell",
  },
  {
    key: "6",
    dateAccomplished: "2024-10-6",
    workDone: "Had a in person meeting to discuss best solution",
    membersParticipated: "All Team members",
  },
  {
    key: "7",
    dateAccomplished: "2024-10-6",
    workDone: "Reached out to professors in school of optomitry",
    membersParticipated: "Selvin",
  },
  {
    key: "8",
    dateAccomplished: "2024-10-6",
    workDone: "Started to apply to Awards",
    membersParticipated: "Timothy",
  },
  {
    key: "9",
    dateAccomplished: "2024-10-12",
    workDone: "Emailed optometry profs",
    membersParticipated: "Selvin",
  },
  {
    key: "10",
    dateAccomplished: "2024-10-13",
    workDone: "Researched ML",
    membersParticipated: "Russell",
  },
  {
    key: "11",
    dateAccomplished: "2024-10-14",
    workDone: "Worked on machine learning repo",
    membersParticipated: "Russell",
  },
  {
    key: "12",
    dateAccomplished: "2024-10-15",
    workDone: "Researched and reached out to suppliers for parts",
    membersParticipated: "Selvin",
  },
  {
    key: "13",
    dateAccomplished: "2024-10-15",
    workDone: "Ramping up on ML model",
    membersParticipated: "Timothy",
  },
  {
    key: "14",
    dateAccomplished: "2024-10-16",
    workDone: "Started work on backend of project",
    membersParticipated: "Harsimrat",
  },
  {
    key: "15",
    dateAccomplished: "2024-10-16",
    workDone: "Got working ML models",
    membersParticipated: "Russell",
  },
  {
    key: "16",
    dateAccomplished: "2024-10-17",
    workDone: "Researched Prof Vasudevan Lakshminarayanan papers",
    membersParticipated: "Timothy",
  },
  {
    key: "17",
    dateAccomplished: "2024-10-18",
    workDone: "Met with prof Vasudevan Lakshminarayanan",
    membersParticipated: "All Team members",
  },
  {
    key: "18",
    dateAccomplished: "2024-10-28",
    workDone: "Completed YOLO model for ML image cropping about the ONH region",
    membersParticipated: "Russell",
  },
  {
    key: "19",
    dateAccomplished: "2024-10-31",
    workDone: "Met with prof Vengu",
    membersParticipated: "All Team members",
  },
  {
    key: "20",
    dateAccomplished: "2024-10-21",
    workDone: "Got working model for glaucoma diagnosis with F1 Score of 0.8",
    membersParticipated: "Russell",
  },
  {
    key: "21",
    dateAccomplished: "2024-10-16",
    workDone: "Setup ML repo for training, testing",
    membersParticipated: "Russell",
  },
  {
    key: "22",
    dateAccomplished: "2024-11-2",
    workDone: "Researched different boards for the kiosk",
    membersParticipated: "Timothy",
  },
  {
    key: "23",
    dateAccomplished: "2024-11-3",
    workDone: "Worked on detailed design presentation",
    membersParticipated: "Timothy",
  },
  {
    key: "23",
    dateAccomplished: "2024-10-22",
    workDone: "Completed preliminary optical simulations",
    membersParticipated: "Selvin",
  },
  {
    key: "24",
    dateAccomplished: "2024-10-30",
    workDone: "Contacted supplier regarding camera customization",
    membersParticipated: "Selvin",
  },
  {
    key: "25",
    dateAccomplished: "2024-10-29",
    workDone: "Generated potential parts list",
    membersParticipated: "Selvin",
  },
  {
    key: "26",
    dateAccomplished: "2024-10-31",
    workDone: "Designed backend flow",
    membersParticipated: "Harsimrat",
  },
  {
    key: "27",
    dateAccomplished: "2024-11-2",
    workDone: "Researched on AWS products for backend",
    membersParticipated: "Harsimrat",
  },
  {
    key: "28",
    dateAccomplished: "2024-11-16",
    workDone: "Got access to a 6k image dataset by emailing researchers",
    membersParticipated: "Russell",
  },
  {
    key: "29",
    dateAccomplished: "2024-11-29",
    workDone: "Tuned Model more reached a safe 85% F1 score",
    membersParticipated: "Russell",
  },
  {
    key: "30",
    dateAccomplished: "2024-11-15",
    workDone: "Placed order for optometry test model for alignment and testing",
    membersParticipated: "Selvin",
  },
  {
    key: "31",
    dateAccomplished: "2024-11-28",
    workDone: "Placed camera and lens parts order",
    membersParticipated: "Selvin",
  },
  {
    key: "32",
    dateAccomplished: "2024-11-23",
    workDone: "Finished optical system design",
    membersParticipated: "Selvin",
  },
  {
    key: "33",
    dateAccomplished: "2024-11-29",
    workDone: "Finished optical simulations",
    membersParticipated: "Selvin",
  },
  {
    key: "34",
    dateAccomplished: "2024-11-23",
    workDone: "Finished design CAD model",
    membersParticipated: "Selvin",
  },
  {
    key: "35",
    dateAccomplished: "2024-11-20",
    workDone: "Selected raspberry pi 5 board for computing",
    membersParticipated: "Timothy",
  },
  {
    key: "36",
    dateAccomplished: "2024-12-1",
    workDone:
      "Placed order raspberry pi 5 board and Adafruit/Lumex LEDs for optics system",
    membersParticipated: "Timothy",
  },
  {
    key: "37",
    dateAccomplished: "2024-11-23",
    workDone: "Created local version of SQL table",
    membersParticipated: "Harsimrat",
  },
  {
    key: "38",
    dateAccomplished: "2024-11-26",
    workDone: "Created test api to acces a fake backend",
    membersParticipated: "Harsimrat",
  },
  {
    key: "39",
    dateAccomplished: "2024-12-2",
    workDone: "Won the Yuen Family Foundation Awards for Healthy Aging - 2024",
    membersParticipated: "All Team members",
  },
  {
    key: "40",
    dateAccomplished: "2024-12-2",
    workDone: "Worked on and completed the Final Report",
    membersParticipated: "All Team members",
  },
];

export default logs;
